# Controls when the workflow will run
on:
  # Allows you to run this workflow manually target the Actions tab
  workflow_dispatch:

name: Build
jobs:
  build:
    name: Build ${{matrix.name}}-${{matrix.runson}}_${{ matrix.env }}
    strategy:
      matrix:
        include:
          - { runson: 'windows-latest',   runsontype: 'windows',    sys: 'mingw64', env: 'x86_64', name: 'Worm', binsuffix: '.exe', }
          - { runson: 'windows-latest',   runsontype: 'windows',    sys: 'mingw32', env: 'i686',   name: 'Worm', binsuffix: '.exe', }
          - { runson: 'ubuntu-24.04',     runsontype: 'linux',      sys: 'usr',     env: 'x64',    name: 'Worm', binsuffix: '',     }
          - { runson: 'ubuntu-22.04',     runsontype: 'linux',      sys: 'usr',     env: 'x64',    name: 'Worm', binsuffix: '',     }
          - { runson: 'ubuntu-24.04-arm', runsontype: 'linux',      sys: 'usr',     env: 'arm64',  name: 'Worm', binsuffix: '',     }
          - { runson: 'ubuntu-22.04-arm', runsontype: 'linux',      sys: 'usr',     env: 'arm64',  name: 'Worm', binsuffix: '',     }
          - { runson: 'macos-13',         runsontype: 'mac',        sys: 'usr',     env: 'intel',  name: 'Worm', binsuffix: '',     }
          - { runson: 'macos-14',         runsontype: 'mac',        sys: 'usr',     env: 'arm64',  name: 'Worm', binsuffix: '',     }
          - { runson: 'macos-15',         runsontype: 'mac',        sys: 'usr',     env: 'arm64',  name: 'Worm', binsuffix: '',     }
          - { runson: 'macos-15-intel',   runsontype: 'mac',        sys: 'usr',     env: 'x64',    name: 'Worm', binsuffix: '',     }          
          - { runson: 'macos-26',         runsontype: 'mac',        sys: 'usr',     env: 'arm64',  name: 'Worm', binsuffix: '',     }
          - { runson: 'ubuntu-24.04',     runsontype: 'emscripten', sys: 'usr',     env: 'web',    name: 'Worm', binsuffix: '',     }

    runs-on: ${{matrix.runson}}    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - if: ${{ matrix.runsontype == 'windows'}}
        name: Setup Msys
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            base-devel
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-make
            mingw-w64-${{matrix.env}}-cmake
            mingw-w64-${{matrix.env}}-ninja
            
          
      - if: ${{ matrix.runsontype == 'linux'}}
        name: install libsdl 2/3 dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libglib2.0-dev libcairo2-dev libpango1.0-dev libsndio-dev libasound2-dev libdbus-1-dev libibus-1.0-dev libjack-dev libdrm-dev libudev-dev libgl1-mesa-dev libgles2-mesa-dev libsndio-dev libwayland-dev libxkbcommon-dev wayland-protocols qtbase5-dev libpulse-dev libsamplerate0-dev libx11-dev libxext-dev libxcursor-dev libxi-dev libxfixes-dev libxrandr-dev libxss-dev libdrm-dev libgbm-dev libwayland-dev libxkbcommon-dev
          #try these 1 by 1 as they are different on different ubuntu versions
          for i in libsndio7.0 libsndio7.1 libsndio7.2 libsndio-dev libasound2-dev libdecor-0-dev libdecoration0-dev libpipewire-0.3-dev libpipewire-dev; do sudo apt-get install -y $i || true; done
                  
      - if: ${{ matrix.runsontype == 'windows'}}
        name: Build Game Windows
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -DUSE_VENDORED_SDL=1 ..
          ninja
          
      - if: ${{ matrix.runsontype != 'windows' && matrix.runsontype != 'emscripten'}}
        name: Build Game Other
        run: |
          mkdir build
          cd build      
          cmake -DUSE_VENDORED_SDL=1 ..
          make
      
      - if: ${{ matrix.runsontype == 'emscripten'}}
        name: build
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..
          mkdir build
          cd build
          emcmake cmake -DUSE_VENDORED_SDL=1 -DSDLTTF_VENDORED=1 -S ..
          emmake make
          cd ..
          cp ./build/Worm.* ./html
          mv ./html ./Release
          
      - if: ${{ matrix.runsontype == 'mac'}}
        name: Copy Game And Assets Mac
        run: |
          mkdir ./Release
          mkdir "./Release/${{matrix.name}}.app"
          mkdir "./Release/${{matrix.name}}.app/Contents"
          mkdir "./Release/${{matrix.name}}.app/Contents/MacOS"
          mkdir "./Release/${{matrix.name}}.app/Contents/Resources"
          cp "build/${{matrix.name}}" "./Release/${{matrix.name}}.app/Contents/MacOS/${{matrix.name}}"
          cp -r "fonts" "./Release/${{matrix.name}}.app/Contents/Resources/fonts"
          cp ./README.md "./Release/"
          cp ./LICENSE "./Release/"
          
          #for PNG
          mkdir icon.iconset
          sips -z 16 16 "./Worm.png" --out icon.iconset/icon_16x16.png
          sips -z 32 32 "./Worm.png" --out icon.iconset/icon_16x16@2x.png
          sips -z 32 32 "./Worm.png" --out icon.iconset/icon_32x32.png
          sips -z 64 64 "./Worm.png" --out icon.iconset/icon_32x32@2x.png
          sips -z 128 128 "./Worm.png" --out icon.iconset/icon_128x128.png
          sips -z 256 256 "./Worm.png" --out icon.iconset/icon_128x128@2x.png
          sips -z 256 256 "./Worm.png" --out icon.iconset/icon_256x256.png
          sips -z 512 512 "./Worm.png" --out icon.iconset/icon_256x256@2x.png
          sips -z 512 512 "./Worm.png" --out icon.iconset/icon_512x512.png
          sips -z 1024 1024 "./Worm.png" --out icon.iconset/icon_512x512@2x.png
          iconutil -c icns icon.iconset -o ./icon.icns
          mv ./icon.icns "./Release/${{matrix.name}}.app/Contents/Resources/icon.icns"
          
          #create PList
          echo "<?xml version='1.0' encoding='UTF-8'?>" > "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "<!DOCTYPE plist PUBLIC '-//Apple Computer//DTD PLIST 1.0//EN' 'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "<plist version='1.0'>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "  <dict>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>CFBundleExecutable</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <string>Worm</string>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>CFBundleIdentifier</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <string>com.github.joyrider3774.Worm</string>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>CFBundleName</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <string>Worm</string>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>CFBundleIconFile</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <string>icon.icns</string>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>CFBundleShortVersionString</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <string>0.01</string>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>CFBundleInfoDictionaryVersion</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <string>6.0</string>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>CFBundlePackageType</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <string>APPL</string>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>IFMajorVersion</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <integer>0</integer>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <key>IFMinorVersion</key>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "    <integer>1</integer>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "  </dict>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
          echo "</plist>" >> "./Release/${{matrix.name}}.app/Contents/Info.plist"
      
      - if: ${{ matrix.runsontype == 'mac'}}
        name: Ad Hoc Code sign Appl Bundle (Mac)
        run: |
          codesign --force --deep -s - "./Release/${{matrix.name}}.app"
          
      - if: ${{ matrix.runsontype != 'mac' && matrix.runsontype != 'emscripten'}}
        name: Copy Game And Assets Other
        run: |
          mkdir ./Release
          mkdir "./Release/${{matrix.name}}"
          cp "build/${{matrix.name}}${{matrix.binsuffix}}" "./Release/${{matrix.name}}/"
          cp -r "fonts" "./Release/${{matrix.name}}/fonts"
          cp ./README.md "./Release/${{matrix.name}}/"
          cp ./LICENSE "./Release/${{matrix.name}}/"
        
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.name}}-${{matrix.runson}}_${{ matrix.env }}
          path: ./Release/
